### PR TITLE
edits for clarity

### PR DESCRIPTION
**Pull request by saupchurch**
additional clarity for some endpoints and removes reference to a draft document

### CODE REVIEW

**Comment by emi80** [comment]
It looks good to me

**Comment by jb-adams** [comment]
Also looks good to me

**Comment by jb-adams** [comment]
have we made the change from rnaget -> RNAget in all files? I see rnaget in README.md

**Comment by jb-adams** [comment]
files I've found that still say rnaget instead of RNAget:
- README.md
- MAINTAINERS.md
- rnaget-openapi.yaml (wouldn't have to change everything here, but I think the value of info.title should be changed)
- testing/README.md

**Comment by saupchurch** [comment]
thanks @jb-adams - updated with missing name conversions

**Pull request merged**
