### PR TITLE
added tag descriptions to html

### PR DESCRIPTION
**Pull request by jb-adams**
@saupchurch I've got the tag descriptions (e.g. the expressions metadata table) into the HTML doc. Can you have a look? You should be able to view the HTML doc by downloading `index.html`and viewing it in browser.

### CODE REVIEW

**Comment by saupchurch** [comment]
Looking good so far.  There seems to be an error in the "Meaning of zero" section with the italics.

**Comment by jb-adams** [comment]
> Looking good so far. There seems to be an error in the "Meaning of zero" section with the italics.

Thanks, just edited it. Can you check again?

**Comment by saupchurch** [comment]
Text is properly in italics now.  There is still an odd character in place of the dash.  It looks like it's in the openAPI yaml.  While I'd prefer to not touch the yaml at this point I think replacing a "funny dash" with a "dash" should be ok.

**Comment by jb-adams** [comment]
> Text is properly in italics now. There is still an odd character in place of the dash. It looks like it's in the openAPI yaml. While I'd prefer to not touch the yaml at this point I think replacing a "funny dash" with a "dash" should be ok.

Ok, do you want to start another PR for that and then I can rerun the HTML build? Otherwise, we can leave it in till after tomorrow and we can merge this PR.

**Comment by saupchurch** [comment]
I'll make a PR to change the dash character for merge after tomorrow.  This PR is ok to merge.

**Pull request merged**
